version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
jobs:
    build-test-monitor:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: curl https://snyk.docs.apiary.io/api-description-document -o snyk.apib
            - run: ./prepare-apib.sh snyk.apib
            - run: npm run build-generators-only
            - run: npm run convert-to-swagger
            - run: npm run prepare-swagger
            - run: npm run generate-classes test
            - run: npm run build-generators-and-abstraction
            - run: npm run generate-classes test
            - run: npm run format
            - run: npm run build
            - run: npm run generate-test-cases
            - run: npm run generate-test-fixtures
            - run: npm run format
            - run: npm test
            - run: npm run clean-generated-classes
            - run: npm run generate-classes
            - run: npm run clean-for-release
            - run: npx semantic-release
    build-test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: curl https://snyk.docs.apiary.io/api-description-document -o snyk.apib
            - run: ./prepare-apib.sh snyk.apib
            - run: npm run build-generators-only
            - run: npm run convert-to-swagger
            - run: npm run prepare-swagger
            - run: npm run generate-classes test
            - run: npm run build-generators-and-abstraction
            - run: npm run generate-classes test
            - run: npm run format
            - run: npm run build
            - run: npm run generate-test-cases
            - run: npm run generate-test-fixtures
            - run: npm run format
            - run: npm test
    build-test-from-fork:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - run: npx tsc
workflows:
    version: 2
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-monitor:
                context: SNYK

    build-test-monitor:
        jobs:
            - build-test-monitor:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/
